[[redirects]]
  from = "/privacy"
  to = "https://www.freeprivacypolicy.com/privacy/view/875885d5e7d99ef0298801e3ec79167a"
  force = true
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
